### ISSUE TITLE
media_bynder_preprocess_image_style() breaks image styles

### ISSUE THREAD

**Issue by mortenson** [Bynder/drupal-media-bynder#34]
```
function media_bynder_preprocess_image_style(&$variables) {
    $variables['uri'] = $variables['path'];
}
```

This code breaks image styles on my site :crying_cat_face: . `uri` isn't a normal variable in [theme_image_style](https://api.drupal.org/api/drupal/modules%21image%21image.module/function/theme_image_style/7), and should always be empty when this hook is called. What is this trying to do and how can we add more conditions or move this logic to another hook?

**Comment by saltednut** [comment]
It is possible that the Bynder module is inserting the uri key for assets delivered via Bynder. In this case, they would need to check to see if that key exists before re-assigning it. It looks like we should be able to insert a simple logic check here to allow this to function for core Drupal and Bynder overrides.

**Comment by mortenson** [comment]
Looks like #35 was pulled as a result of this.

**Comment by happylinks** [comment]
Sorry for not letting you guys know, indeed https://github.com/Bynder/drupal-media-bynder/pull/35 was made to fix this problem. Please let us know if there is still something wrong.
