### ISSUE TITLE
not able to install media_bynder

### ISSUE THREAD

**Issue by anupriyavij** [Bynder/drupal-media-bynder#40]
Hi 

I have downloaded the code for drupal-media-bynder. After installing the required modules, when i tried installing the media_bynder module in Drupal 7, there was an error
Parse error: syntax error, unexpected '[' in /media_bynder/includes/media_bynder.formatters.inc on line 257

When I tried solving this error then a new error in admin.inc occurred at getAll()->['media'].

So basically I am not able to install the module. Can you please help me out with this issue.

**Comment by MichielRans** [comment]
Hi, 

Can you tell us which version of PHP you're using?

**Comment by anupriyavij** [comment]
5.3.6

**Comment by MichielRans** [comment]
Is it possible to upgrade to PHP 5.4? At this point our Drupal plugin requires PHP 5.4 as a minimum version.

**Comment by GoZOo** [comment]
You should add this minimum PHP requirement to .info files : https://www.drupal.org/node/542202#php
