### ISSUE TITLE
Running composer update gives error "Your requirements could not be resolved to an installable set of packages."

### ISSUE THREAD

**Issue by neyensp** [Bynder/drupal-media-bynder#53]
Not possible to find package "bynder/bynder-php-sdk"

Problem 1
    - Installation request for bynder/drupal-media-bynder dev-develop -> satisfiable by bynder/drupal-media-bynder[dev-develop].
    - bynder/drupal-media-bynder dev-develop requires bynder/bynder-php-sdk dev-develop -> no matching package found.

**Comment by jfcsantos** [comment]
Hi there @neyensp, I'm afraid this shouldn't have been merged yet, it's still work in progress and we will announce it properly once it's ready. 
I'll revert the changes now.
