### ISSUE TITLE
PHP versions

### ISSUE THREAD

**Issue by ghost** [Bynder/drupal-media-bynder#55]
The syntax in the module relies on environments to be PHP version 5.4 and above.

When enabling this on an environment with an older version, errors similar to the below occur:

`Parse error: syntax error, unexpected '[' in /sites/all/modules/media_bynder/includes/media_bynder.utils.inc on line 44`

Could this also be included in the documentation as well please?

**Comment by jfcsantos** [comment]
Hi there. Please note that this version of the module is no longer supported. 
You can get the new module in the [Bynder Drupal project page](https://www.drupal.org/project/bynder).

Please open any issue you might encounter in there.
