### ISSUE TITLE
Plans for a D8 Release?

### ISSUE THREAD

**Issue by drogers98** [Bynder/drupal-media-bynder#56]
Howdy, I am evaluating Bynder for a client install, and am wondering if there is a D8 version of this module in the works?

Cheers.

**Comment by jfcsantos** [comment]
Hi there @drogers98 
I'm sorry we haven't updated this repo before, but this module is no longer supported. We moved everything to drupal.org and you can get both the new D7 and the D8 version of the module in the [Bynder project page](https://www.drupal.org/project/bynder).

Let me know there if you have any issues.
Cheers
